#########################################
#  Educational Cloud Platform Service   #
#    Computer Engineering, KMITL        #
#########################################
# For Frontend

version: '3.5'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ce-cloud-frontend
    container_name: frontend
    # env_file: .env
    # environment:
    #   DB_HOST: db
    #   DB_USER: ${DB_USER}
    #   DB_PASS: ${DB_PASS}
    #   DB_NAME: ${DB_NAME} 
    networks:
      - ce-cloud-network
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app

networks:
  ce-cloud-network:
